# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Weather_Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(590, 460)
        Home.setMinimumSize(QtCore.QSize(590, 460))
        Home.setMaximumSize(QtCore.QSize(590, 460))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Home.setFont(font)
        Home.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Home.setWindowIcon(icon)
        Home.setAutoFillBackground(False)
        Home.setStyleSheet("background-color: #31CCFE    ;\n"
"")
        Home.setIconSize(QtCore.QSize(55, 24))
        Home.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        Home.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.Sensor_data = QtWidgets.QLabel(self.centralwidget)
        self.Sensor_data.setGeometry(QtCore.QRect(20, 20, 300, 300))
        self.Sensor_data.setStyleSheet("background-color: #00BFFF;\n"
"border: 6px solid #FEFEFE;\n"
"border-top-left-radius: 70px;\n"
"border-bottom-right-radius: 70px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.Sensor_data.setText("")
        self.Sensor_data.setObjectName("Sensor_data")
        self.Sensor_data_temp = QtWidgets.QLabel(self.centralwidget)
        self.Sensor_data_temp.setGeometry(QtCore.QRect(50, 60, 140, 140))
        font = QtGui.QFont()
        font.setPointSize(85)
        font.setBold(True)
        font.setWeight(75)
        self.Sensor_data_temp.setFont(font)
        self.Sensor_data_temp.setStyleSheet("background-color: #00BFFF;\n"
"color: white;\n"
"")
        #self.Sensor_data_temp.setTextFormat(QtCore.Qt.MarkdownText)
        self.Sensor_data_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Sensor_data_temp.setObjectName("Sensor_data_temp")
        self.Sensor_data_humidity = QtWidgets.QLabel(self.centralwidget)
        self.Sensor_data_humidity.setGeometry(QtCore.QRect(200, 220, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Sensor_data_humidity.setFont(font)
        self.Sensor_data_humidity.setStyleSheet("background-color: #00BFFF;\n"
"color:white;")
        self.Sensor_data_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.Sensor_data_humidity.setObjectName("Sensor_data_humidity")
        self.WeatherBit_data = QtWidgets.QLabel(self.centralwidget)
        self.WeatherBit_data.setGeometry(QtCore.QRect(340, 30, 227, 191))
        self.WeatherBit_data.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"border: 6px solid #FEFEFE;\n"
"border-top-right-radius: 70px;\n"
"border-bottom-left-radius: 70px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.WeatherBit_data.setText("")
        self.WeatherBit_data.setObjectName("WeatherBit_data")
        self.OWM_data = QtWidgets.QLabel(self.centralwidget)
        self.OWM_data.setGeometry(QtCore.QRect(340, 230, 227, 191))
        self.OWM_data.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"border: 6px solid #FEFEFE;\n"
"border-top-right-radius: 70px;\n"
"border-bottom-left-radius: 70px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.OWM_data.setText("")
        self.OWM_data.setScaledContents(True)
        self.OWM_data.setAlignment(QtCore.Qt.AlignCenter)
        self.OWM_data.setObjectName("OWM_data")
        self.WeatherBit_data_temp = QtWidgets.QLabel(self.centralwidget)
        self.WeatherBit_data_temp.setGeometry(QtCore.QRect(370, 40, 125, 105))
        font = QtGui.QFont()
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.WeatherBit_data_temp.setFont(font)
        self.WeatherBit_data_temp.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color: white;\n"
"")
        #self.WeatherBit_data_temp.setTextFormat(QtCore.Qt.MarkdownText)
        self.WeatherBit_data_temp.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.WeatherBit_data_temp.setWordWrap(False)
        self.WeatherBit_data_temp.setObjectName("WeatherBit_data_temp")
        self.WeatherBit_data_humidity = QtWidgets.QLabel(self.centralwidget)
        self.WeatherBit_data_humidity.setGeometry(QtCore.QRect(480, 150, 75, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.WeatherBit_data_humidity.setFont(font)
        self.WeatherBit_data_humidity.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color:white;")
        self.WeatherBit_data_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.WeatherBit_data_humidity.setObjectName("WeatherBit_data_humidity")
        self.OWM_data_temp = QtWidgets.QLabel(self.centralwidget)
        self.OWM_data_temp.setGeometry(QtCore.QRect(370, 240, 125, 105))
        font = QtGui.QFont()
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.OWM_data_temp.setFont(font)
        self.OWM_data_temp.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color: white;\n"
"")
        #self.OWM_data_temp.setTextFormat(QtCore.Qt.MarkdownText)
        self.OWM_data_temp.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.OWM_data_temp.setWordWrap(False)
        self.OWM_data_temp.setObjectName("OWM_data_temp")
        self.OWM_data_humidity = QtWidgets.QLabel(self.centralwidget)
        self.OWM_data_humidity.setGeometry(QtCore.QRect(480, 350, 75, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.OWM_data_humidity.setFont(font)
        self.OWM_data_humidity.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color:white;")
        self.OWM_data_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.OWM_data_humidity.setObjectName("OWM_data_humidity")
        self.about_weatherbit = QtWidgets.QLabel(self.centralwidget)
        self.about_weatherbit.setGeometry(QtCore.QRect(360, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.about_weatherbit.setFont(font)
        self.about_weatherbit.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color: white;\n"
"border: 6px solid rgb(255, 69, 0);\n"
"border-radius: 20px;\n"
"")
        self.about_weatherbit.setObjectName("about_weatherbit")
        self.about_owm = QtWidgets.QLabel(self.centralwidget)
        self.about_owm.setGeometry(QtCore.QRect(360, 360, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.about_owm.setFont(font)
        self.about_owm.setStyleSheet("background-color :rgb(255, 69, 0);\n"
"color: white;\n"
"border: 6px solid rgb(255, 69, 0);\n"
"border-radius: 20px;\n"
"")
        self.about_owm.setObjectName("about_owm")
        self.about_localdata = QtWidgets.QLabel(self.centralwidget)
        self.about_localdata.setGeometry(QtCore.QRect(40, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.about_localdata.setFont(font)
        self.about_localdata.setStyleSheet("background-color: #00BFFF;\n"
"color: white;\n"
"\n"
"")
        self.about_localdata.setAlignment(QtCore.Qt.AlignCenter)
        self.about_localdata.setObjectName("about_localdata")
        self.About = QtWidgets.QPushButton(self.centralwidget)
        self.About.setGeometry(QtCore.QRect(20, 340, 101, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.About.sizePolicy().hasHeightForWidth())
        self.About.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.About.setFont(font)
        self.About.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.About.setMouseTracking(False)
        self.About.setStyleSheet("color: white;\n"
"background-color: #00BFFF;\n"
"border: 6px solid #FEFEFE;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-right-radius: 6px;\n"
"border-bottom-left-radius: 6px;")
        self.About.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/2940537-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About.setIcon(icon1)
        self.About.setIconSize(QtCore.QSize(60, 110))
        self.About.setCheckable(False)
        self.About.setAutoDefault(False)
        self.About.setObjectName("About")
        self.Warning = QtWidgets.QLabel(self.centralwidget)
        self.Warning.setGeometry(QtCore.QRect(120, 350, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Warning.setFont(font)
        self.Warning.setStyleSheet("color: rgb(200, 0, 0);")
        self.Warning.setAlignment(QtCore.Qt.AlignCenter)
        self.Warning.setWordWrap(False)
        self.Warning.setObjectName("Warning")
        Home.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Home)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 590, 25))
        self.menuBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuBar.setObjectName("menuBar")
        self.menuHome = QtWidgets.QMenu(self.menuBar)
        self.menuHome.setObjectName("menuHome")
        Home.setMenuBar(self.menuBar)
        self.actionHome = QtWidgets.QAction(Home)
        self.actionHome.setObjectName("actionHome")
        self.actionSensor_Live_Mode = QtWidgets.QAction(Home)
        self.actionSensor_Live_Mode.setObjectName("actionSensor_Live_Mode")
        self.actionWeather_for_Week = QtWidgets.QAction(Home)
        self.actionWeather_for_Week.setObjectName("actionWeather_for_Week")
        self.actionHourly_Weather = QtWidgets.QAction(Home)
        self.actionHourly_Weather.setObjectName("actionHourly_Weather")
        self.actionStatistic = QtWidgets.QAction(Home)
        self.actionStatistic.setObjectName("actionStatistic")
        self.menuHome.addAction(self.actionHome)
        self.menuHome.addSeparator()
        self.menuHome.addAction(self.actionSensor_Live_Mode)
        self.menuHome.addSeparator()
        self.menuHome.addAction(self.actionWeather_for_Week)
        self.menuHome.addAction(self.actionHourly_Weather)
        self.menuHome.addSeparator()
        self.menuHome.addAction(self.actionStatistic)
        self.menuBar.addAction(self.menuHome.menuAction())

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)


    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.Sensor_data_temp.setText(_translate("Home", "t"))
        self.Sensor_data_humidity.setText(_translate("Home", "h"))
        self.WeatherBit_data_temp.setText(_translate("Home", "t"))
        self.WeatherBit_data_humidity.setText(_translate("Home", "h"))
        self.OWM_data_temp.setText(_translate("Home", "t"))
        self.OWM_data_humidity.setText(_translate("Home", "h"))
        self.about_weatherbit.setText(_translate("Home", "Weather get from \n"
"     WeatherBit"))
        self.about_owm.setText(_translate("Home", "Weather get from \n"
"     OpenWeatherMap"))
        self.about_localdata.setText(_translate("Home", "Weather get from  \n"
"     local sensor"))
        self.Warning.setText(_translate("Home", "Some API is paid, so it can work \n"
"bad or can not work. \n"
" You can email me for that."))
        self.menuHome.setTitle(_translate("Home", "Menu"))
        self.actionHome.setText(_translate("Home", "Home"))
        self.actionSensor_Live_Mode.setText(_translate("Home", "Sensor Live Mode"))
        self.actionWeather_for_Week.setText(_translate("Home", "Weather for Week"))
        self.actionHourly_Weather.setText(_translate("Home", "Hourly Weather"))
        self.actionStatistic.setText(_translate("Home", "Statistic"))
# import 1_rc


