# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Weather_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(360, 360)
        About.setMinimumSize(QtCore.QSize(360, 360))
        About.setMaximumSize(QtCore.QSize(360, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/2940537-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        About.setStyleSheet("background-color: #31CCFE;")
        self.centralwidget = QtWidgets.QWidget(About)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 341, 281))
        self.label.setStyleSheet("color: white;\n"
"background-color: #00BFFF;\n"
"border: 6px solid #FEFEFE;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-right-radius: 6px;\n"
"border-bottom-left-radius: 6px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(44, 4, 270, 60))
        self.label_2.setStyleSheet("background-color:#00BFFF;\n"
"border: 6px solid #FEFEFE;\n"
"border-radius:23px;\n"
"")
        self.label_2.setObjectName("label_2")
        About.setCentralWidget(self.centralwidget)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Created by: </span><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#ffffff;\">Սուրեն Փարսյան</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Facebook: </span><a href=\"https://www.facebook.com/profile.php?id=100009193080852\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">Suren Parsian</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Instagram</span><a href=\"https://www.facebook.com/profile.php?id=100009193080852\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">: </span></a><a href=\"https://www.instagram.com/parsyan_066/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">parsyan_066</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Email</span><a href=\"https://www.instagram.com/parsyan_066/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">:</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.instagram.com/parsyan_066/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">parsyan_suren@mail.ru</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.instagram.com/parsyan_066/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">parsyansuren@gmail.com</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">GitHub</span><a href=\"https://www.instagram.com/parsyan_066/\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">: </span></a><a href=\"https://github.com/Suren76/Projects/tree/main/DigiCode_Weather\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#ffffff;\">Suren76</span></a></p></body></html>"))
        self.label_2.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">About Weather</span></p></body></html>"))



